apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - pvc-pihole-root.yaml
#  - secret-ui.yaml
  - service-tcp.yaml
#  - service-udp.yaml