apiVersion: v1
kind: Service

metadata:
  name: pihole-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole

spec:
  selector:
    app: pihole

  type: ClusterIP
  externalTrafficPolicy: Local
#  loadBalancerIP: {{ .Values.service.ip }}

  ports:

    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP

    - name: dhcp-udp
      port: 67
      targetPort: dhcp-udp
      protocol: UDP