apiVersion: v1
kind: Service

metadata:
  name: pihole-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole

spec:
  selector:
    app: pihole

  type: LoadBalancer
  externalTrafficPolicy: Local
#  loadBalancerIP: {{ .Values.service.ip }}

  ports:
    - name: http
      port: 80
      targetPort: http-tcp
      protocol: TCP

    - name: https
      port: 443
      targetPort: https-tcp
      protocol: TCP

    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP